In [1]:
import torch
import numpy as np
import pandas as pd


In [2]:
data = pd.read_csv('/content/House Price India.csv')
print(data)

               id   Date  number of bedrooms  number of bathrooms  \
0      6762810145  42491                   5                 2.50   
1      6762810635  42491                   4                 2.50   
2      6762810998  42491                   5                 2.75   
3      6762812605  42491                   4                 2.50   
4      6762812919  42491                   3                 2.00   
...           ...    ...                 ...                  ...   
14615  6762830250  42734                   2                 1.50   
14616  6762830339  42734                   3                 2.00   
14617  6762830618  42734                   2                 1.00   
14618  6762830709  42734                   4                 1.00   
14619  6762831463  42734                   3                 1.00   

       living area  lot area  number of floors  waterfront present  \
0             3650      9050               2.0                   0   
1             2920      4000   

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14620 entries, 0 to 14619
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   id                                     14620 non-null  int64  
 1   Date                                   14620 non-null  int64  
 2   number of bedrooms                     14620 non-null  int64  
 3   number of bathrooms                    14620 non-null  float64
 4   living area                            14620 non-null  int64  
 5   lot area                               14620 non-null  int64  
 6   number of floors                       14620 non-null  float64
 7   waterfront present                     14620 non-null  int64  
 8   number of views                        14620 non-null  int64  
 9   condition of the house                 14620 non-null  int64  
 10  grade of the house                     14620 non-null  int64  
 11  Ar

In [4]:
columnas_eliminar = ['id','Postal Code','Date']
data = data.drop(columnas_eliminar, axis=1)

In [5]:
#convertir a entero,
data['number of bathrooms'] =data['number of bathrooms'].astype(int)
data['number of floors'] =data['number of floors'].astype(int)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14620 entries, 0 to 14619
Data columns (total 20 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   number of bedrooms                     14620 non-null  int64  
 1   number of bathrooms                    14620 non-null  int64  
 2   living area                            14620 non-null  int64  
 3   lot area                               14620 non-null  int64  
 4   number of floors                       14620 non-null  int64  
 5   waterfront present                     14620 non-null  int64  
 6   number of views                        14620 non-null  int64  
 7   condition of the house                 14620 non-null  int64  
 8   grade of the house                     14620 non-null  int64  
 9   Area of the house(excluding basement)  14620 non-null  int64  
 10  Area of the basement                   14620 non-null  int64  
 11  Bu

In [7]:
data.to_csv("nuevodata.csv",index=False)

In [8]:
data = np.loadtxt("/content/nuevodata.csv", delimiter=',',skiprows=1)
# print(data)
X = data[:, :19]
Y = data[:, 19]
print(X.shape)
print(Y.shape)

(14620, 19)
(14620,)


In [9]:
print(data)

[[5.00e+00 2.00e+00 3.65e+03 ... 2.00e+00 5.80e+01 2.38e+06]
 [4.00e+00 2.00e+00 2.92e+03 ... 2.00e+00 5.10e+01 1.40e+06]
 [5.00e+00 2.00e+00 2.91e+03 ... 1.00e+00 5.30e+01 1.20e+06]
 ...
 [2.00e+00 1.00e+00 1.07e+03 ... 2.00e+00 6.40e+01 2.09e+05]
 [4.00e+00 1.00e+00 1.03e+03 ... 3.00e+00 5.40e+01 2.05e+05]
 [3.00e+00 1.00e+00 9.00e+02 ... 2.00e+00 5.50e+01 1.46e+05]]


In [27]:
X_train=X[:13000]
X_test=X[13000:]
# Calcular la media y la desviación estándar de cada característica en el conjunto de entrenamiento.
mean = np.mean(X_train, axis=0)
std = np.std(X_train, axis=0)
# Normalizar los datos de entrenamiento.
X_train_normalized = (X_train - mean) / std
# Normalizar los datos de prueba utilizando la misma media y desviación estándar.
X_test_normalized = (X_test - mean) / std

y_train= Y[:13000]
y_test= Y[13000:]


In [11]:
print(X_train_normalized)

[[ 1.72705986  0.31915298  1.66913586 ... -0.28333361 -0.01489274
  -0.77654586]
 [ 0.6618334   0.31915298  0.88310036 ... -0.33749037 -0.01489274
  -1.56144964]
 [ 1.72705986  0.31915298  0.87233275 ... -0.23691354 -1.2402448
  -1.33719142]
 ...
 [-0.40339307  0.31915298 -0.6566678  ... -0.19931327 -0.01489274
   1.46603639]
 [-0.40339307 -1.03495562 -1.09813979 ... -0.4061534  -1.2402448
   1.46603639]
 [-0.40339307 -1.03495562 -0.86125238 ... -0.207166   -0.01489274
  -0.32802941]]


In [54]:
def softmax(x):
    return torch.exp(x) / torch.exp(x).sum(axis=-1,keepdims=True)

In [13]:
print(X.shape)
print(Y.shape)
print("*"*25)
print(X_train_normalized.shape)
print(X_test_normalized.shape)
print(y_train.shape)
print(y_test.shape)

(14620, 19)
(14620,)
*************************
(13000, 19)
(1620, 19)
(13000,)
(1620,)


In [14]:
torch.cuda.is_available()

True

In [48]:
#class LinearRegressionModel(nn.Module):
#    def __init__(self, input_size):
#        super(LinearRegressionModel, self).__init__()
#        self.linear = nn.Linear(input_size, 1)  # Una capa lineal con una sola salida.
#
#    def forward(self, x):
#        return self.linear(x)
class ModeloPersonalizado(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        super(ModeloPersonalizado, self).__init__()
        self.fc1 = torch.nn.Linear(D_in, H)
        self.relu = torch.nn.ReLU()
        self.fc2 = torch.nn.Linear(H, D_out)  # El tamaño de salida debe coincidir con la dimensión de tus etiquetas Y

    def forward(self, x):
       x = self.fc1(x)
       x = self.relu(x)
       x = self.fc2(x)
       return x
#class ModeloConRegularizacionL1(torch.nn.Module):
#    def __init__(self, D_in, H, D_out, l1_reg):
#        super(ModeloConRegularizacionL1, self).__init__()
#        self.fc1 = torch.nn.Linear(D_in, H)
#        self.relu = torch.nn.ReLU()
#        self.fc2 = torch.nn.Linear(H, D_out)

        # Agregar regularización L2 a las capas lineales
 #       self.l1_reg = l1_reg

 #   def forward(self, x):
 #       x = self.fc1(x)
 #       x = self.relu(x)
 #       x = self.fc2(x)
 #       return x

In [49]:
model=ModeloPersonalizado(19,50,1)
#model = ModeloConRegularizacionL1(19, 100, 1, l1_reg=0.01)  # Ajusta l2_reg según tu elección
# Codigo para saber si el modelo esta votando los datos en las cantidades correctas
x_prueba = torch.randn(64, 19)
print(x_prueba)
outputs = model(x_prueba)
outputs.shape

tensor([[-1.0117,  1.6629, -0.1525,  ..., -2.1700,  0.6719,  0.5765],
        [-0.0904, -0.5126, -0.5900,  ..., -0.9554,  0.3880, -1.0020],
        [ 0.8688, -0.6521,  0.2755,  ...,  0.8373,  1.3977, -0.8739],
        ...,
        [-2.4119, -1.2422,  0.1859,  ...,  1.7144,  0.8394, -0.3220],
        [-0.0789,  0.9216, -0.6489,  ..., -0.3944,  0.1172,  2.3723],
        [ 0.5168,  0.9953,  0.7675,  ..., -0.0872,  0.2100, -0.0745]])


torch.Size([64, 1])

In [52]:
import torch.nn as nn
model.to("cuda")
#criterion = nn.MSELoss()
#loss = criterion(outputs, targets)
criterion = nn.L1Loss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.05)  # Ajusta lr según lo que funcione mejor
#optimizer = torch.optim.SGD(model.parameters(), lr=0.8)
X_t = torch.from_numpy(X_train_normalized).float().cuda()
Y_t = torch.from_numpy(y_train).float().cuda()
epochs = 100
log_each = 10
l = []
model.train()
for e in range(1, epochs+1):

    # forward
    y_pred = model(X_t)
    #print("y_pred:", y_pred)
    # loss
    loss = criterion(y_pred, Y_t)
    l.append(loss.item())

    # ponemos a cero los gradientes
    optimizer.zero_grad()

    # Backprop (calculamos todos los gradientes automáticamente)
    loss.backward()
    # update de los pesos
    optimizer.step()

    if not e % log_each:
        print(f"Epoch {e}/{epochs} Loss {np.mean(l):.5f}")


Epoch 10/100 Loss 224883.15313
Epoch 20/100 Loss 224352.42109
Epoch 30/100 Loss 223924.16198
Epoch 40/100 Loss 223577.83594
Epoch 50/100 Loss 223296.72031
Epoch 60/100 Loss 223067.09349
Epoch 70/100 Loss 222877.69687
Epoch 80/100 Loss 222719.86582
Epoch 90/100 Loss 222587.01458
Epoch 100/100 Loss 222474.12547


In [55]:
from sklearn.metrics import accuracy_score

def evaluate(x):
    model.eval()
    y_pred = model(x)
    y_probas = softmax(y_pred)
    return torch.argmax(y_probas, axis=1)
y_pred = evaluate(torch.from_numpy(X_test).float().cuda())
accuracy_score(y_test, y_pred.cpu().numpy())

0.0